# Generated by Django 3.2.9 on 2021-11-20 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('date', models.DateField(auto_now_add=True)),
                ('review', models.TextField(max_length=300)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='news.news')),
            ],
        ),
    ]
