# Generated by Django 3.2.9 on 2021-11-14 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='news',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
